### ISSUE TITLE
[Enhancement] Add contributing guidelines, code of conduct, readme, issue and PR templates, docs

### ISSUE THREAD

**Issue by sh7dm** [sh7dm/vue-simple-icons#4]
# TODO
- [x] `CONTRIBUTING.md`
- [x] `CODE_OF_CONDUCT.md`
- [x] `ISSUE_TEMPLATE.md`
  - [x] Bug report
  - [x] Feature request
- [x] `PULL_REQUEST_TEMPLATE.md`
- [ ] Docs (e.g. `vuepress`). See #13
- [x] `README.md`

**Comment by sh7dm** [comment]
@gabrieledarrigo @ericcornelissen What do you think about using Vuepress for docs?

**Comment by ericcornelissen** [comment]
A note for the Contributing Guidelines (i.e. CONTRIBUTING.md), we should include notes that we use the following development tools:

- commitlint: for linting commit messages, with a brief explanation of the format we use (currently [config-conventional](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional) as far as I know).
- Jest: for testing, when you add/change code testing is required.
- yarn: we don't use _npm_, instead we use _yarn_ (to avoid issues like #2)
- eslint: for linting typescript code.

And perhaps more...? I will try to write something up if I find the time 🙂

**Comment by sh7dm** [comment]
```markdown
## Note:
1. We use commitlint for linting commit messages
2. We use commitizen for creating commit messages.
3. Use Jest for testing. Don't forget to add tests for new features and please make sure that all tests are passing.
4. We use `yarn` instead of `npm`, please don't use `npm`, because we already have `yarn.lock`.
5. We are linting TypeScript code using ESLint. You can lint and test your code with `yarn test` command.
```

## Note:
1. We use commitlint for linting commit messages
2. We use commitizen for creating commit messages.
3. Use Jest for testing. Don't forget to add tests for new features and please make sure that all tests are passing.
4. We use `yarn` instead of `npm`, please don't use `npm`, because we already have `yarn.lock`.
5. We are linting TypeScript code using ESLint. You can lint and test your code with `yarn test` command.

**Comment by ericcornelissen** [comment]
Good start @sh7dm, I made some adjustments below ⬇️ Do you agree?
- Updated wording with the main goal of generalizing.
- Use MarkDown smart numbering.
- Added links for ease of use.
- Added `$` to indicate that this is a CLI command.
- Added Emoji (optional).

* * *

```markdown
## Note:
1. 📦 We use _[yarn](https://yarnpkg.com/en/)_ rather then _[npm](https://www.npmjs.com/)_ as a package managing. Please **do not** use `npm` as it may cause unwanted changes.
1. 📝 We use the [conventional commit message](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional) format and enforce it using [commitlint](https://marionebl.github.io/commitlint/#/). We recommend utilizing [commitizen](http://commitizen.github.io/cz-cli/) through the `$ yarn commit` command.
1. ✅ We use [Jest](https://jestjs.io/) for testing. Don't forget to add tests for new features and make sure that all tests are passing.
1. 👕 We lint TypeScript code using ESLint. You can lint your code with `$ yarn test` command and automatically fix any issues using `$ yarn fix`.
1. 📖 Don't forget to add or update documentation in `docs/` when you add or change a feature. We use [VuePress](https://vuepress.vuejs.org/) to automatically generate web-based documentation from this.
```

## Note:
1. 📦 We use _[yarn](https://yarnpkg.com/en/)_ rather then _[npm](https://www.npmjs.com/)_ as a package managing. Please **do not** use _npm_ as it may cause unwanted changes.
1. 📝 We use the [conventional commit message](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional) format and enforce it using [commitlint](https://marionebl.github.io/commitlint/#/). We recommend utilizing [commitizen](http://commitizen.github.io/cz-cli/) through the `$ yarn commit` command.
1. ✅ We use [Jest](https://jestjs.io/) for testing. Don't forget to add tests for new features and make sure that all tests are passing.
1. 👕 We lint TypeScript code using ESLint. You can lint your code with `$ yarn test` command and automatically fix any issues using `$ yarn fix`.
1. 📖 Don't forget to add or update documentation in `docs/` when you add or change a feature. We use [VuePress](https://vuepress.vuejs.org/) to automatically generate web-based documentation from this.

**Comment by sh7dm** [comment]
@ericcornelissen :+1: Looks great!
